scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.12
    upper_threshold: 3.5
    lower_replacement_value: 0.12
    upper_replacement_value: 3.5
